import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { data as D, economy as E, arena as A, hours as H, adventure as X } from '../netlify/functions/lib/gehstockmon-rules.mjs';
import { createHandler } from '../netlify/functions/gehstockmon.mjs';
let passed=0,sequence=0;
async function test(name,fn){await fn();passed++;console.log('ok',name);}
export function memoryStore(){let data=null,version=0;return{get data(){return data;},async getWithMetadata(){return data?{data:structuredClone(data),etag:String(version)}:null;},async setJSON(key,next,opts){await new Promise(setImmediate);if((opts.onlyIfNew&&data)||(opts.onlyIfMatch!==undefined&&opts.onlyIfMatch!==String(version)))return{modified:false};data=structuredClone(next);version++;return{modified:true};}};}
function codeAt(index){let codes=[];for(let n=0;n<10000;n++){const code=String(n).padStart(4,'0'),text='code:'+code+':gehstock:hideout:2026:kellergewoelbe';let h=0x811c9dc5;for(const c of text){h^=c.charCodeAt(0);h=(h+(h<<1)+(h<<4)+(h<<7)+(h<<8)+(h<<24))>>>0;}if(h%97===0)codes.push(code);}return codes[index];}
const ca=codeAt(0),cb=codeAt(1),stamp=Date.parse('2026-09-17T07:00:00+02:00');
async function call(handler,code,op,data={}){const response=await handler(new Request('http://localhost/api/gehstockmon',{method:'POST',body:JSON.stringify({code,name:code===ca?'Test A':'Test B',op,requestId:'request-'+(++sequence),...data})}));return{status:response.status,...await response.json()};}
function action(b){const u=b.teams[0][b.active[0]],e=b.teams[1][b.active[1]];if(b.phase==='replace')return{kind:'switch',slot:b.teams[0].findIndex((k)=>k.hp>0)};if(u.charges>0&&((u.role===2&&u.hp<u.maxHp*.67)||(u.role===1&&e.hp<=e.maxHp*.35)||(u.role===3&&!e.weakened)))return{kind:'move',move:'special'};return{kind:'move',move:b.round>=u.powerReady?'power':'strike'};}
async function win(handler,code,territoryId=1){let r=await call(handler,code,'world');r=await call(handler,code,'arena_start',{territoryId,version:r.territories[territoryId-1].version,squad:r.profile.truppe});assert.equal(r.status,200);for(let i=0;r.arena.phase!=='finished'&&i<80;i++){r=await call(handler,code,'arena_turn',{battleId:r.arena.id,revision:r.arena.revision,action:action(r.arena)});assert.equal(r.status,200,r.error);}assert.equal(r.arena.winner,'wir');return r;}

await test('42 distinct images, nine biomes and chosen 2h/1h timers',()=>{assert.equal(D.KATALOG.length,42);assert.equal(new Set(D.KATALOG.map(k=>k.id)).size,42);assert.equal(D.FELDER.length,9);assert.equal(new Set(D.BIOME.map(b=>b.terrain)).size,9);for(const k of D.KATALOG)assert.ok(fs.existsSync('src/assets/'+k.bild+'.webp'));assert.equal(E.EGG_TIME,7200000);assert.equal(E.HATCH_TIME,3600000);});
await test('Old saves keep collection and migrate currency once',()=>{const old={essenz:240,geschafft:[1,3],besitz:['moosling']};const p=D.neuerStand(old,stamp);assert.equal(p.gold,360);assert.ok(p.besitz.includes('moosling'));assert.equal(p.outposts[1].eggAt,stamp);p.gold=10;assert.equal(D.neuerStand(p,stamp+100).gold,10);assert.equal(D.neuerStand(p,stamp+100).outposts[1].eggAt,stamp);});
await test('Income, exact egg threshold, fractional time and backwards clocks',()=>{const p=D.neuerStand(null,stamp);E.capture(p,1,stamp);const post=p.outposts[1],gold=p.gold;E.tick(p,stamp+E.EGG_TIME-1);assert.equal(post.eggStock,0);E.tick(p,stamp+E.EGG_TIME);assert.equal(post.eggStock,1);assert.equal(p.gold,gold+40);E.tick(p,stamp);E.tick(p,stamp+E.EGG_TIME);assert.equal(p.gold,gold+40);E.tick(p,stamp+20*E.HOUR);assert.equal(post.eggStock,3);assert.equal(post.eggAt,stamp+20*E.HOUR);});
await test('Upgrade settles elapsed time at old income and changes defense',()=>{const p=D.neuerStand(null,stamp);E.capture(p,1,stamp);const before=p.gold,post=p.outposts[1];E.upgrade(p,post,stamp+E.HOUR);assert.equal(p.gold,before+20-120);assert.equal(post.level,2);E.tick(p,stamp+2*E.HOUR);assert.equal(p.gold,before+20-120+35);assert.equal(E.LEVELS[2].bonus,.12);});
await test('Egg collection, incubation slots and hatching cannot skip time',()=>{const p=D.neuerStand(null,stamp);E.capture(p,1,stamp);E.tick(p,stamp+6*E.HOUR);assert.equal(E.collect(p,p.outposts[1],1,stamp+6*E.HOUR),3);for(const egg of p.eggs)E.incubate(p,egg.id,stamp+6*E.HOUR);const id=p.eggs[0].id;assert.throws(()=>E.hatch(p,id,stamp+7*E.HOUR-1,.2),/noch nicht/);const mon=E.hatch(p,id,stamp+7*E.HOUR,.2);assert.ok(mon);assert.equal(p.besitz.length,5);assert.throws(()=>E.hatch(p,id,stamp+7*E.HOUR,.2));assert.equal(p.eggs.length,2);});
await test('All missing Mons hatch without duplicates; complete collection yields gold',()=>{const p=D.neuerStand(null,stamp);for(let i=0;i<D.KATALOG.length-3;i++){p.eggs=[{id:'egg'+i,territoryId:1,startedAt:stamp,readyAt:stamp+E.HOUR,producedAt:stamp}];E.hatch(p,'egg'+i,stamp+E.HOUR,.5);}assert.equal(new Set(p.besitz).size,42);assert.equal(p.gold,255);});
await test('Common starters can capture their first biome; stronger Mons can clear all five',()=>{const starters=D.neuerStand().truppe.map(D.mon);assert.ok(starters.every(k=>k.seltenheit===0));assert.ok(A.stats(D.mon('glutfuchs')).ang<A.stats(D.mon('sonnenkoenig')).ang);for(const f of D.FELDER.slice(0,5)){const team=f.id===1?starters:['titanenkrone','sonnenkoenig','sternengeweih','leerenwyrm'].map(D.mon);let b=A.create(team,A.defenders(f.id),{territoryId:f.id,level:1});for(let i=0;b.phase!=='finished'&&i<80;i++)b=A.turn(b,action(b));assert.equal(b.winner,'wir',f.name);}const old=['bollwerk','klinge','waerter','spaeher'];assert.deepEqual(D.neuerStand({besitz:old,truppe:old}).besitz,old);});
await test('Invalid moves are immutable; power cooldown blocks repeated use',()=>{let b=A.create(D.KATALOG.slice(0,4),A.defenders(1),{}),before=JSON.stringify(b);assert.throws(()=>A.turn(b,{kind:'move',move:'delete-enemy'}));assert.equal(JSON.stringify(b),before);b=A.turn(b,{kind:'move',move:'power'});assert.throws(()=>A.turn(b,{kind:'move',move:'power'}),/nicht verfügbar/);assert.equal(b.revision,1);});
await test('Fainted enemies do not retaliate and forced switching is free',()=>{let b=A.create([D.mon('spaeher'),D.mon('klinge')],[D.mon('bollwerk')],{});b.teams[1][0].hp=1;const hp=b.teams[0][0].hp;b=A.turn(b,{kind:'move',move:'strike'});assert.equal(b.winner,'wir');assert.equal(b.teams[0][0].hp,hp);b=A.create([D.mon('bollwerk'),D.mon('klinge')],[D.mon('spaeher')],{});b.teams[0][0].hp=1;b=A.turn(b,{kind:'move',move:'strike'});assert.equal(b.phase,'replace');const round=b.round;b=A.turn(b,{kind:'switch',slot:1});assert.equal(b.round,round);assert.equal(b.teams[0][1].hp,b.teams[0][1].maxHp);});
await test('Invalid authentication and legacy summon cannot mutate the world',async()=>{const store=memoryStore(),h=createHandler({store,now:()=>stamp});assert.equal((await call(h,'bad','join')).status,401);assert.equal(store.data,null);assert.equal((await call(h,ca,'summon')).status,400);assert.equal(store.data,null);});
await test('Server advances individual turns, resumes, and awards conquest exactly once',async()=>{const store=memoryStore(),h=createHandler({store,now:()=>stamp});await call(h,ca,'join');let r=await call(h,ca,'arena_start',{territoryId:1,version:1,squad:D.neuerStand().truppe});assert.equal(r.profile.gold,180);assert.equal(r.territories[0].ownerId,null);const turn={battleId:r.arena.id,revision:0,action:{kind:'move',move:'power'},requestId:'same-turn-0001'};r=await call(h,ca,'arena_turn',turn);const replay=await call(h,ca,'arena_turn',turn);assert.equal(replay.arena.revision,r.arena.revision);assert.equal(replay.duplicate,true);assert.equal((await call(h,ca,'arena_turn',{...turn,requestId:'stale-turn-0002'})).status,409);const resumed=await call(h,ca,'join');assert.equal(resumed.arena.revision,1);while(r.arena.phase!=='finished'){r=await call(h,ca,'arena_turn',{battleId:r.arena.id,revision:r.arena.revision,action:action(r.arena),requestId:'finish-'+r.arena.revision});}assert.equal(r.arena.winner,'wir');assert.equal(r.profile.gold,220);assert.equal(r.territories[0].ownerId,r.playerId);assert.equal((await call(h,ca,'world')).profile.gold,220);});
await test('Flee and idle expiry never conquer or award gold',async()=>{let time=stamp;const h=createHandler({store:memoryStore(),now:()=>time});await call(h,ca,'join');let r=await call(h,ca,'arena_start',{territoryId:1,version:1,squad:D.neuerStand().truppe});r=await call(h,ca,'arena_flee',{battleId:r.arena.id,revision:0});assert.equal(r.arena.winner,'fled');assert.equal(r.profile.gold,180);r=await call(h,ca,'arena_start',{territoryId:1,version:1,squad:D.neuerStand().truppe});time+=21*60000;r=await call(h,ca,'world');assert.equal(r.arena.winner,'expired');assert.equal(r.territories[0].ownerId,null);});
await test('Server eggs, timed hatching and upgrade retries are authoritative',async()=>{let time=stamp;const store=memoryStore(),h=createHandler({store,now:()=>time,random:()=>.2});await call(h,ca,'join');let r=await win(h,ca);time+=E.EGG_TIME;r=await call(h,ca,'collect',{territoryId:1,requestId:'collect-once-0001'});assert.equal(r.profile.eggs.length,1);assert.equal((await call(h,ca,'collect',{territoryId:1,requestId:'collect-once-0001'})).profile.eggs.length,1);const egg=r.profile.eggs[0];await call(h,ca,'incubate',{eggId:egg.id});assert.equal((await call(h,ca,'hatch',{eggId:egg.id})).status,400);time+=E.HATCH_TIME;r=await call(h,ca,'hatch',{eggId:egg.id,requestId:'hatch-once-0001'});assert.ok(r.monId);assert.equal(r.profile.besitz.length,5);assert.equal((await call(h,ca,'hatch',{eggId:egg.id,requestId:'hatch-once-0001'})).profile.besitz.length,5);r=await call(h,ca,'upgrade',{territoryId:1,requestId:'upgrade-once-001'});const gold=r.profile.gold;assert.equal(r.territories[0].level,2);const retry=await call(h,ca,'upgrade',{territoryId:1,requestId:'upgrade-once-001'});assert.equal(retry.profile.gold,gold);assert.equal(retry.territories[0].level,2);await call(h,cb,'join');assert.equal((await call(h,cb,'upgrade',{territoryId:1})).status,403);});
await test('Competing final turns award only one conquest',async()=>{const store=memoryStore(),h=createHandler({store,now:()=>stamp});const pa=await call(h,ca,'join'),pb=await call(h,cb,'join');for(const code of[ca,cb])await call(h,code,'arena_start',{territoryId:1,version:1,squad:D.neuerStand().truppe});for(const p of Object.values(store.data.players)){p.arena.teams[1].forEach((u,i)=>u.hp=i===0?1:0);p.arena.teams[0][0].speed=100;}const results=await Promise.all([ca,cb].map((code,i)=>{const p=store.data.players[i===0?pa.playerId:pb.playerId];return call(h,code,'arena_turn',{battleId:p.arena.id,revision:0,action:{kind:'move',move:'strike'}});}));assert.deepEqual(results.map(r=>r.arena.winner).sort(),['stale','wir']);assert.equal(Object.values(store.data.players).reduce((s,p)=>s+p.gold,0),400);});
await test('Client recovers response loss without a second action and isolates accounts',async()=>{const store=memoryStore(),h=createHandler({store,now:()=>stamp});await call(h,ca,'join');await call(h,cb,'join');const values=new Map();let lose=true;const SG={gehstockmon:{},env:{},auth:{aktuell:{code:ca}},storage:{get:(k,d)=>values.has(k)?structuredClone(values.get(k)):d,set:(k,v)=>values.set(k,structuredClone(v)),del:k=>values.delete(k)}};const context=vm.createContext({SG,window:{},AbortController,setTimeout,clearTimeout,fetch:async(url,opts)=>{const r=await h(new Request('http://localhost'+url,opts));if(lose){lose=false;throw new TypeError('response lost');}return r;}});const source=fs.readFileSync('src/games/gehstockmon/2-online.js','utf8');vm.runInContext(source,context);await assert.rejects(SG.gehstockmon.online.request('arena_start',{territoryId:1,version:1,squad:D.neuerStand().truppe}),/Antwort unbestätigt/);assert.ok(SG.gehstockmon.online.pending());SG.auth.aktuell.code=cb;assert.equal(SG.gehstockmon.online.pending(),null);SG.auth.aktuell.code=ca;vm.runInContext(source,context);const r=await SG.gehstockmon.online.request('resume');assert.equal(r.duplicate,true);assert.equal(r.arena.revision,0);assert.equal(r.profile.gold,180);assert.equal(SG.gehstockmon.online.pending(),null);});
await test('Online-only UI: auto-join, server progression, reload, peers and lost-response recovery',async()=>{const {checkUi}=await import('./gehstockmon-ui-test.mjs');let time={value:stamp};await checkUi(D,E,A,createHandler({store:memoryStore(),presenceStore:memoryStore(),now:()=>time.value,random:()=>.2}),ca,time,cb);});
await test('Two players share ownership, attack saved defenses and retain independent collections',async()=>{const store=memoryStore(),h=createHandler({store,now:()=>stamp});const pa=await call(h,ca,'join');await call(h,cb,'join');const conquered=await win(h,ca);let other=await call(h,cb,'world');assert.equal(other.territories[0].ownerId,pa.playerId);assert.equal(other.profile.gold,180);assert.equal(other.territories[0].version,conquered.territories[0].version);other=await call(h,cb,'arena_start',{territoryId:1,version:other.territories[0].version,squad:other.profile.truppe});assert.equal(other.status,200);assert.deepEqual(other.arena.teams[1].map(u=>u.monId),pa.profile.truppe);for(let i=0;other.arena.phase!=='finished'&&i<80;i++)other=await call(h,cb,'arena_turn',{battleId:other.arena.id,revision:other.arena.revision,action:action(other.arena)});assert.equal(other.status,200);assert.equal(other.arena.winner,'wir');const first=await call(h,ca,'world');assert.equal(first.territories[0].ownerId,other.playerId);assert.equal(first.profile.besitz.length,4);assert.equal(first.territories[0].eggStock,0);assert.equal(first.reports.at(-1).defenderId,pa.playerId);});
await test('Offline catalog hides online-only games while preserving offline games',()=>{const SG={util:{},games:{},order:[],offline:false};vm.runInNewContext(fs.readFileSync('src/core/registry.js','utf8'),{SG});SG.register({id:'gehstockmon',onlineOnly:true});SG.register({id:'puzzle'});assert.equal(SG.list().length,2);SG.offline=true;assert.equal(SG.list().length,1);assert.equal(SG.list()[0].id,'puzzle');});
await test('Map migration preserves eggs, collection and earned income and chooses one owner per biome',async()=>{
  const store=memoryStore(),h=createHandler({store,now:()=>stamp});const a=await call(h,ca,'join'),b=await call(h,cb,'join');
  const old=Array.from({length:25},(_,i)=>({...structuredClone(store.data.territories[i%5]),id:i+1,...E.outpost(null,stamp-E.HOUR)}));
  Object.assign(old[0],{ownerId:a.playerId,ownerName:'First',capturedAt:stamp-2*E.HOUR});
  Object.assign(old[5],{ownerId:b.playerId,ownerName:'Second',capturedAt:stamp-E.HOUR,level:2});
  store.data.territories=old;delete store.data.mapVersion;
  const p=store.data.players[a.playerId];p.besitz=['bollwerk','klinge','waerter','spaeher'];p.truppe=p.besitz.slice();p.eggs=[{id:'legacy-egg',territoryId:24,producedAt:stamp-E.HOUR,startedAt:stamp-E.HOUR,readyAt:stamp}];
  p.arena=A.create(p.truppe.map(D.mon),A.defenders(1),{territoryId:21,now:stamp});
  const migrated=await call(h,ca,'world');assert.equal(migrated.territories.length,9);assert.equal(migrated.territories[0].ownerId,b.playerId);assert.equal(migrated.territories[0].level,2);assert.equal(migrated.profile.gold,200);assert.deepEqual(migrated.profile.besitz,p.besitz);assert.equal(migrated.profile.eggs[0].territoryId,4);assert.equal(migrated.profile.eggs[0].readyAt,stamp);assert.equal(migrated.arena.winner,'map_changed');assert.equal(migrated.arena.territoryId,1);assert.equal(store.data.previousMap.territories.length,25);
  const repeated=await call(h,ca,'world');assert.equal(repeated.profile.gold,migrated.profile.gold);assert.equal((await call(h,ca,'arena_start',{territoryId:24,version:1,squad:p.truppe})).status,400);
});
await test('Presence shares positions, expires departures and cannot change progression or impersonate players',async()=>{
  let time=stamp;const store=memoryStore(),presence=memoryStore(),h=createHandler({store,presenceStore:presence,now:()=>time});
  assert.equal((await call(h,ca,'presence',{position:{x:0,z:0,heading:0}})).status,409);
  const a=await call(h,ca,'join'),b=await call(h,cb,'join'),snapshot=JSON.stringify(store.data);
  const pair=await Promise.all([call(h,ca,'presence',{position:{...a.spawn,heading:1},playerId:b.playerId}),call(h,cb,'presence',{position:{...b.spawn,heading:-1}})]);
  assert.ok(pair.every(r=>r.status===200));assert.equal(Object.keys(presence.data.players).length,2);
  let r=await call(h,ca,'presence',{position:{...a.spawn,heading:1}});assert.equal(r.peers.length,1);assert.equal(r.peers[0].id,b.playerId);assert.equal(r.peers[0].x,b.spawn.x);assert.ok(!('code' in r.peers[0])&&!('profile' in r.peers[0]));assert.equal(JSON.stringify(store.data),snapshot);
  assert.equal((await call(h,ca,'presence',{position:{x:9999,z:1,heading:0}})).status,400);assert.equal((await call(h,ca,'presence',{position:{x:'0',z:1,heading:0}})).status,400);
  time+=15001;r=await call(h,ca,'presence',{position:{...a.spawn,heading:1}});assert.equal(r.peers.length,0);assert.equal(Object.keys(presence.data.players).length,1);
});
await test('Berlin opening boundaries include Friday, block weekends and follow daylight saving',()=>{
  for(const [day,close] of [[14,13],[15,13],[16,14],[17,15],[18,13]]) {
    const start=Date.parse('2026-09-'+day+'T07:00:00+02:00'),end=start+(close-7)*E.HOUR;
    assert.equal(H.access(start-1).open,false);assert.equal(H.access(start).open,true);assert.equal(H.access(end-1).open,true);assert.equal(H.access(end).open,false);
  }
  for(const date of ['2026-09-19T00:00:00+02:00','2026-09-20T12:00:00+02:00','2026-09-21T06:59:59+02:00'])assert.equal(H.access(Date.parse(date)).open,false);
  for(const [closed,open] of [['2026-10-24T12:00:00+02:00','2026-10-26T07:00:00+01:00'],['2027-03-27T12:00:00+01:00','2027-03-29T07:00:00+02:00']])assert.equal(H.access(Date.parse(closed)).nextOpenAt,Date.parse(open));
});
await test('Closed server rejects every operation and spoofed client clocks without changing stores',async()=>{
  let time=Date.parse('2026-09-18T12:59:59+02:00');const store=memoryStore(),presence=memoryStore(),h=createHandler({store,presenceStore:presence,now:()=>time});await call(h,ca,'join');
  const before=JSON.stringify(store.data);time+=1000;
  for(const op of ['join','world','presence','arena_start','arena_turn','arena_flee','collect','incubate','hatch','upgrade','defend',...X.OPS]) {
    const r=await call(h,ca,op,{serverTime:stamp,now:stamp,position:{x:0,z:0,heading:0}});assert.equal(r.status,423,op);assert.equal(r.access.open,false);assert.equal(r.profile,undefined);
  }
  assert.equal(JSON.stringify(store.data),before);assert.equal(presence.data,null);
  time=Date.parse('2026-09-21T07:00:00+02:00');assert.equal((await call(h,ca,'join')).status,200);
  const lateStore=memoryStore();let checks=0;const late=createHandler({store:lateStore,now:()=>Date.parse('2026-09-21T12:59:59.999+02:00')+(checks++?1:0)});
  assert.equal((await call(late,ca,'join')).status,423);assert.equal(lateStore.data,null,'a request crossing closing time cannot commit');
});
await test('Each completed weekend gives two eggs per held post once, preserving overflow and ownership rewards',async()=>{
  let time=Date.parse('2026-09-11T07:00:00+02:00');const store=memoryStore(),h=createHandler({store,now:()=>time});const a=await call(h,ca,'join');await call(h,cb,'join');
  const p=store.data.players[a.playerId];for(const t of store.data.territories)Object.assign(t,{ownerId:a.playerId,...E.outpost(null,time)});
  p.eggs=Array.from({length:11},(_,i)=>({id:'saved-'+i,territoryId:1,producedAt:time,startedAt:time,readyAt:time+E.HOUR}));
  time=Date.parse('2026-09-14T07:00:00+02:00');const results=await Promise.all([call(h,ca,'join'),call(h,ca,'join')]);
  assert.equal(results.reduce((sum,r)=>sum+(r.weekendDelivery||0),0),1);let r=await call(h,ca,'world');assert.equal(r.profile.eggs.length,12);assert.equal(Object.values(r.profile.weekendEggs).reduce((a,b)=>a+b,0),17);assert.equal(r.profile.eggs[0].readyAt,Date.parse('2026-09-11T08:00:00+02:00'));
  r=await call(h,ca,'hatch',{eggId:'saved-0',requestId:'weekend-hatch-once'});assert.equal(r.weekendDelivery,1);assert.equal(r.profile.eggs.length,12);assert.equal(Object.values(r.profile.weekendEggs).reduce((a,b)=>a+b,0),16);
  const retry=await call(h,ca,'hatch',{eggId:'saved-0',requestId:'weekend-hatch-once'});assert.equal(retry.duplicate,true);assert.deepEqual(retry.profile.weekendEggs,r.profile.weekendEggs);
  const other=await call(h,cb,'world');assert.equal(other.profile.eggs.length,0);assert.deepEqual(other.profile.weekendEggs,{});
  // Previously earned gifts belong to the old owner even if a territory changes later.
  store.data.territories[0].ownerId=other.playerId;Object.assign(store.data.territories[0],E.outpost(null,time));
  time=Date.parse('2026-09-28T07:00:00+02:00');r=await call(h,ca,'join');assert.equal(Object.values(r.profile.weekendEggs).reduce((a,b)=>a+b,0),48);
  const b=await call(h,cb,'join');assert.equal(b.profile.eggs.length,4);assert.equal((await call(h,cb,'join')).profile.eggs.length,4);
});
await test('Weekend replaces normal egg production, retains partial cycles and ignores DST length',()=>{
  for(const [friday,monday] of [['2026-09-18T23:00:00+02:00','2026-09-21T00:00:00+02:00'],['2026-10-23T23:00:00+02:00','2026-10-26T00:00:00+01:00'],['2027-03-26T23:00:00+01:00','2027-03-29T00:00:00+02:00']]) {
    const start=Date.parse(friday),end=Date.parse(monday),p=D.neuerStand(null,start),post=E.outpost(null,start);E.settle(p,post,end);assert.equal(post.eggStock,0);assert.equal(E.nextEggAt(post),end+E.HOUR);E.weekend(p,post,1,end);assert.equal(p.weekendEggs[1],2);E.weekend(p,post,1,end);assert.equal(p.weekendEggs[1],2);E.settle(p,post,end+E.HOUR);assert.equal(post.eggStock,1);
  }
  assert.equal(H.weekends(Date.parse('2026-09-12T01:00:00+02:00'),Date.parse('2026-09-14T07:00:00+02:00')).count,0,'ownership must precede the weekend');
  assert.equal(H.weekends(0,Date.parse('2026-09-14T07:00:00+02:00')).count,1,'no rewards before introduction');
});
console.log('\n'+passed+' GehstockMon regression checks passed.');
